export enum SocketEvent {
  HELLO = 'hello',
  SONG_START = 'songStart',
  FINISHED = 'finished',
  SOFT_FAILED = 'softFailed',
  FAILED = 'failed',
  MENU = 'menu',
  PAUSE = 'pause',
  RESUME = 'resume',
  NOTE_SPAWNED = 'noteSpawned',
  NOTE_CUT = 'noteCut',
  NOTE_FULLY_CUT = 'noteFullyCut',
  NOTE_MISSED = 'noteMissed',
  BOMB_CUT = 'bombCut',
  BOMB_MISSED = 'bombMissed',
  OBSTACLE_ENTER = 'obstacleEnter',
  OBSTACLE_EXIT = 'obstacleExit',
  SCORE_CHANGED = 'scoreChanged',
  BEATMAP_EVENT = 'beatmapEvent'
}
